In [1]:
import numpy as np
import pandas as pd
import csv

In [2]:
from numpy import dtype

In [3]:
# from numpy import genfromtxt

In [4]:
# my_data = genfromtxt('oil.csv', delimiter = ',', dtype = None, encoding = None)

In [53]:
df = pd.read_csv('oil.csv')

In [6]:
df.head()

Date    Open    High     Low   Close    Vol    Weekday Month  Year
0  10/1/2012  112.14  113.27  110.76  111.40  80055     Monday   Oct  2012
1  10/2/2012  111.40  111.70  110.55  110.55  29332    Tuesday   Oct  2012
2  10/3/2012  110.55  110.59  106.95  107.34  56307  Wednesday   Oct  2012
3  10/4/2012  107.44  111.79  107.24  111.36  61664   Thursday   Oct  2012
4  10/5/2012  111.27  112.09  109.64  111.13  51704     Friday   Oct  2012

In [8]:
import normalization

In [8]:
normalization.normalization(df)

C:\Users\Gurgen\Desktop\Master Degree\1 course\1 half\Python\Group_Project\Marianna_Gurgen\normalization.py:25: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  df[a[i]][j] = (df[a[i]][j] - avg)/(sd)


In [12]:
import descriptive_statistics as ds

In [15]:
ds.summary(df)

Date
Count :  1643
Unique :  1643
Top :  1


Open
Count :  1643
Min :  27.99
1st Q :  49.925
Median :  61.68
3rd Q :  106.97
Max :  117.96
Mean :  74.06831405964707
St. dev :  27.80608273465092


High
Count :  1643
Min :  28.75
1st Q :  50.67
Median :  62.7
3rd Q :  107.845
Max :  118.29
Mean :  74.78076080340847
St. dev :  27.780344052611788


Low
Count :  1643
Min :  27.1
1st Q :  49.25
Median :  60.63
3rd Q :  106.455
Max :  117.74
Mean :  73.32127814972615
St. dev :  27.808711385783646


Close
Count :  1643
Min :  27.79
1st Q :  49.92
Median :  61.87
3rd Q :  107.03
Max :  118.04
Mean :  74.04758368837497
St. dev :  27.808848624480497


Vol
Count :  1643
Min :  0
1st Q :  48471.5
Median :  113728.0
3rd Q :  159089.0
Max :  522586
Mean :  108013.22458916616
St. dev :  72296.2539506527


Weekday
Count :  1643
Unique :  6
Top :  1


Month
Count :  1643
Unique :  12
Top :  1


Year
Count :  1643
Min :  2012
1st Q :  2014.0
Median :  2015.0
3rd Q :  2016.0
Max :  2018
Mean :  2014.90018

In [46]:
def grroup(x, *args):
    values = list(args)
    n = len(values)
    for i in range(n):
        print(x[x[values[i]] == n[i]])

In [47]:
grroup(df, 'Weekday', 'Year')

['Monday', 'Year']
2


In [44]:
df.groupby('Weekday').mean()

Open       High        Low      Close            Vol  \
Weekday                                                                
Friday     74.300554  75.102103  73.467601  74.347601  127484.594096   
Monday     74.278188  75.022283  73.380761  74.141014  112571.485507   
Sunday     74.244607  74.396554  74.042622  74.204007     563.842697   
Thursday   74.094638  74.967899  73.284601  74.154420  132995.304348   
Tuesday    73.764188  74.577148  72.918159  73.736895  129377.797834   
Wednesday  73.738768  74.612609  72.861558  73.713225  141857.873188   

                  Year  
Weekday                 
Friday     2014.900369  
Monday     2014.880435  
Sunday     2014.880150  
Thursday   2014.905797  
Tuesday    2014.924188  
Wednesday  2014.909420

In [82]:
def grroup(df, colname):
    unique_names = df[colname].unique()
    n = len(unique_names)
    new_list = []
    for i in range(n):
        a = df[df[colname]==unique_names[i]]
        return a
   
        

In [84]:
a = grroup(df, 'Weekday')

In [80]:
def grroup(df, colname):
    unique_names = df[colname].unique()
    n = len(unique_names)
    new_list = []
    for i in range(n):
        a = df[df[colname]==unique_names[i]]
        new_list.append(a)  
    return new_list

In [81]:
a = grroup(df, 'Weekday')

In [7]:
import pivots

In [8]:
pivots.pivoting(df, 'Date', 'Weekday', 'Open')

array([[112.14, 0, 0, 0, 0, 0],
       [0, 111.4, 0, 0, 0, 0],
       [0, 0, 110.55, 0, 0, 0],
       ...,
       [0, 0, 70.18, 0, 0, 0],
       [0, 0, 0, 70.09, 0, 0],
       [0, 0, 0, 0, 69.01, 0]], dtype=object)

In [9]:
# ete ham toxern en krknvox ham syunery petqa nory grvi anunn e kdnenq pivotingtable

In [10]:
df = pd.DataFrame({'foo': ['one', 'one', 'one', 'two', 'two',
                           'two'],
                   'bar': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'baz': [1, 2, 3, 4, 5, 6],
                   'zoo': ['x', 'y', 'z', 'q', 'w', 't']})

In [11]:
df.head()

foo bar  baz zoo
0  one   A    1   x
1  one   B    2   y
2  one   C    3   z
3  two   A    4   q
4  two   B    5   w

In [12]:
pivots.pivoting(df, 'foo', 'bar', 'baz')

array([[1, 2, 3],
       [4, 5, 6]], dtype=object)

In [ ]:
def pivoting(df, row, column, values):
    data = df[[row, column,  values]].to_numpy()
    rows, row_pos = np.unique(data[:, 0], return_inverse=True)
    cols, col_pos = np.unique(data[:, 1], return_inverse=True)
    row_pos = np.sort(row_pos)
    col_pos = np.sort(col_pos)
    col_pos = np.tile(np.unique(col_pos), len(row_pos))
    pivot_table = np.zeros((len(rows), len(cols)), dtype=data.dtype)
    pivot_table[row_pos, col_pos[0:len(row_pos)]] = data[:, 2]
    return pivot_table

In [ ]:
def pivottable(df, row, column, values):
    data = df[[row, column,  values]].to_numpy()
    rows, row_pos = np.unique(data[:, 0], return_inverse=True)
    cols, col_pos = np.unique(data[:, 1], return_inverse=True)
    row_pos = np.sort(row_pos)
    col_pos = np.sort(col_pos)
    col_pos = np.tile(np.unique(col_pos), len(row_pos))
    

In [64]:
data = df[['Month', 'Weekday',  'Open']].to_numpy()
rows, row_pos = np.unique(data[:, 0], return_inverse=True)
cols, col_pos = np.unique(data[:, 1], return_inverse=True)

In [65]:
rows

array(['Apr', 'Aug', 'Dec', 'Feb', 'Jan', 'Jul', 'Jun', 'Mar', 'May',
       'Nov', 'Oct', 'Sep'], dtype=object)

In [66]:
cols[0]

'Friday'

In [67]:
np.empty([len(rows), len(cols)]).shape

(12, 6)

In [68]:
new_list = []
for i in range(len(rows)):
    a = df.copy()
    a = a[a['Month']== rows[i]]
    for j in range(len(cols)):
        b = a.copy()
        b = b[b['Weekday'] == cols[j]]
        c = b['Open'].mean()
        new_list.append(c)

In [75]:
col_pos = np.tile(np.unique(col_pos), len(row_pos))
pivot_table = np.zeros((len(rows), len(cols)), dtype=data.dtype)

In [90]:
pivot_table[0, 0] = new_list[0]
new_list[0:10]

[72.19888888888889,
 75.26190476190477,
 72.48619047619049,
 73.32380952380953,
 76.83363636363637,
 74.92363636363638,
 75.3677272727273,
 70.00454545454546,
 72.78818181818181,
 72.63818181818182]

In [95]:
def pivvottable(df, row, column, value):
    data = df[[row, column, value]].to_numpy()
    rows, row_pos = np.unique(data[:, 0], return_inverse = True)
    cols, col_pos = np.unique(data[:, 1], return_inverse = True)
    new_list = []
    for i in range(len(rows)):
        a = df.copy()
        a = a[a[row]== rows[i]]
        for j in range(len(cols)):
            b = a.copy()
            b = b[b[column] == cols[j]]
            c = b[value].mean()
            new_list.append(c)
    pivottable = np.array(new_list).reshape(len(rows), len(cols))
    return pivottable

In [96]:
pivvottable(df, 'Month', 'Weekday', 'Open')

array([[72.19888889, 75.26190476, 72.48619048, 73.32380952, 76.83363636,
        74.92363636],
       [75.36772727, 70.00454545, 72.78818182, 72.63818182, 69.83181818,
        69.87136364],
       [73.6332    , 77.1632    , 77.51666667, 71.7928    , 71.85      ,
        70.2232    ],
       [74.7515    , 72.78      , 74.623     , 74.382     , 74.557     ,
        74.343     ],
       [71.70846154, 70.6048    , 70.52318182, 73.88307692, 69.93807692,
        72.1028    ],
       [71.82727273, 74.15318182, 71.51727273, 74.47909091, 76.59272727,
        76.11956522],
       [74.05761905, 76.20863636, 77.86045455, 73.04454545, 74.41380952,
        74.2547619 ],
       [73.938     , 74.37772727, 75.98652174, 70.89954545, 71.00681818,
        70.76772727],
       [77.54782609, 73.39863636, 73.5125    , 77.98909091, 73.18409091,
        75.55954545],
       [77.57115385, 74.4484    , 74.012     , 76.17115385, 74.8708    ,
        74.05615385],
       [77.33384615, 77.31259259, 75.6412    , 78.

In [102]:
# if you would like to compare results
df.groupby(['Month', "Weekday"]).mean()

Open       High        Low      Close            Vol  \
Month Weekday                                                                
Apr   Friday     72.198889  72.911667  71.253333  72.011111  141810.611111   
      Monday     75.261905  76.180000  74.394762  75.371905  119385.285714   
      Sunday     72.486190  72.635238  72.343333  72.507143     790.476190   
      Thursday   73.323810  74.423810  72.618095  73.722857  132618.714286   
      Tuesday    76.833636  77.732727  75.984545  77.085455  127994.000000   
      Wednesday  74.923636  75.931364  73.938182  74.885909  145115.318182   
Aug   Friday     75.367727  76.331364  74.792273  75.637273  130414.363636   
      Monday     70.004545  70.789091  69.001364  69.821364  129490.500000   
      Sunday     72.788182  72.890455  72.625455  72.723636     365.818182   
      Thursday   72.638182  73.674091  71.893182  72.942273  145354.227273   
      Tuesday    69.831818  70.681818  69.139091  69.929545  133827.772727   
      Wednesday  69.871364  70.605909  69.183636  69.916818  148630.000000   
Dec   Friday     73.633200  74.528000  72.994800  73.880400  109436.720000   
      Monday     77.163200  78.096000  76.106800  76.834800  100183.480000   
      Sunday     77.516667  77.735417  77.314583  77.520417     845.041667   
      Thursday   71.792800  72.592400  71.044800  71.791200  111614.360000   
      Tuesday    71.850000  72.690385  71.125000  71.899231  105583.346154   
      Wednesday  70.223200  71.029200  69.166400  69.882400  120168.360000   
Feb   Friday     74.751500  75.884500  74.225500  75.264000  117021.650000   
      Monday     72.780000  73.632857  71.944762  72.695714  117693.380952   
      Sunday     74.623000  74.796500  74.441500  74.633000     330.250000   
      Thursday   74.382000  75.325000  73.514000  74.557500  144242.250000   
      Tuesday    74.557000  75.471000  73.523500  74.328500  143664.050000   
      Wednesday  74.343000  75.291500  73.317500  74.366000  146979.550000   
Jan   Friday     71.708462  72.580769  70.767308  71.786538  136915.192308   
      Monday     70.604800  71.067600  69.594800  70.065600  102835.600000   
      Sunday     70.523182  70.640455  70.269545  70.418182     702.863636   
      Thursday   73.883077  74.795769  73.125000  73.910769  124811.692308   
      Tuesday    69.938077  70.846923  69.182308  69.791538  144992.269231   
      Wednesday  72.102800  73.005200  71.429200  72.383600  138245.840000   
...                    ...        ...        ...        ...            ...   
Mar   Friday     73.938000  74.756000  73.182000  73.989500  124390.900000   
      Monday     74.377727  75.017273  73.462273  74.271364  110730.500000   
      Sunday     75.986522  76.184783  75.702174  75.916522     754.956522   
      Thursday   70.899545  71.605909  70.097727  70.849545  141264.909091   
      Tuesday    71.006818  71.703182  70.088182  70.712727  132804.500000   
      Wednesday  70.767727  71.608182  70.015000  70.897727  140629.000000   
May   Friday     77.547826  78.262609  76.655217  77.768696  126439.217391   
      Monday     73.398636  73.926364  72.595455  73.200455   88023.090909   
      Sunday     73.512500  73.661500  73.376000  73.513500     403.650000   
      Thursday   77.989091  78.785909  77.074545  78.005000  138520.636364   
      Tuesday    73.184091  73.990000  72.383182  73.225000  126326.818182   
      Wednesday  75.559545  76.343636  74.615909  75.410909  145746.090909   
Nov   Friday     77.571154  78.522308  76.652692  77.574231  124307.884615   
      Monday     74.448400  75.425600  73.622800  74.685600  123901.840000   
      Sunday     74.012000  74.186400  73.785200  73.949600     709.720000   
      Thursday   76.171154  76.852692  75.143846  75.804231  118402.576923   
      Tuesday    74.870800  75.612000  73.813600  74.608000  141213.880000   
      Wednesday  74.056154  75.047692  73.126538  74.044615  157971.230769   
Oct   Friday     77.333846  77.970769  76.28

In [ ]:
for i in range(len(rows)):
    