In [1]:
import numpy as np
import pandas as pd

In [2]:
from numpy import dtype

In [3]:
# from numpy import genfromtxt

In [4]:
# my_data = genfromtxt('oil.csv', delimiter = ',', dtype = None, encoding = None)

In [5]:
df = pd.read_csv('oil.csv')

In [6]:
df.head()

Date    Open    High     Low   Close    Vol    Weekday Month  Year
0  10/1/2012  112.14  113.27  110.76  111.40  80055     Monday   Oct  2012
1  10/2/2012  111.40  111.70  110.55  110.55  29332    Tuesday   Oct  2012
2  10/3/2012  110.55  110.59  106.95  107.34  56307  Wednesday   Oct  2012
3  10/4/2012  107.44  111.79  107.24  111.36  61664   Thursday   Oct  2012
4  10/5/2012  111.27  112.09  109.64  111.13  51704     Friday   Oct  2012

In [7]:
import normalization

In [8]:
normalization.normalization(df)

C:\Users\Gurgen\Desktop\Master Degree\1 course\1 half\Python\Group_Project\Marianna_Gurgen\normalization.py:25: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  df[a[i]][j] = (df[a[i]][j] - avg)/(sd)


Date      Open      High       Low     Close  Vol    Weekday  \
0      10/1/2012  1.369186  1.385485  1.346295  1.343185    0     Monday   
1      10/2/2012  1.342573  1.328970  1.338743  1.312619   -1    Tuesday   
2      10/3/2012  1.312004  1.289014  1.209287  1.197188    0  Wednesday   
3      10/4/2012  1.200158  1.332210  1.219716  1.341746    0   Thursday   
4      10/5/2012  1.337897  1.343009  1.306020  1.333475    0     Friday   
5      10/7/2012  1.332143  1.308452  1.355644  1.329520   -1     Sunday   
6      10/8/2012  1.321714  1.319611  1.309616  1.336712    0     Monday   
7      10/9/2012  1.345450  1.398803  1.356723  1.413306    0    Tuesday   
8     10/10/2012  1.405149  1.426521  1.415697  1.410789    0  Wednesday   
9     10/11/2012  1.414859  1.445959  1.436195  1.464369    0   Thursday   
10    10/12/2012  1.466646  1.442719  1.424328  1.414385    0     Friday   
11    10/14/2012  1.419894  1.399163  1.431160  1.405035   -1     Sunday   
12    10/15/2012  1.403710  1.429401  1.407427  1.453941    0     Monday   
13    10/16/2012  1.447226  1.443079  1.444465  1.426611    0    Tuesday   
14    10/17/2012  1.434998  1.422921  1.419653  1.408272    0  Wednesday   
15    10/18/2012  1.404430  1.398443  1.375422  1.380583    0   Thursday   
16    10/19/2012  1.376019  1.385125  1.315369  1.304348    0     Friday   
17    10/21/2012  1.288628  1.267775  1.308537  1.284570   -1     Sunday   
18    10/22/2012  1.282514  1.302692  1.287320  1.285289    0     Monday   
19    10/23/2012  1.274962  1.260576  1.222233  1.231709    0    Tuesday   
20    10/24/2012  1.231446  1.244018  1.203893  1.214089    0  Wednesday   
21    10/25/2012  1.213105  1.241858  1.227627  1.238901    0   Thursday   
22    10/26/2012  1.240077  1.256976  1.225469  1.282053    0     Friday   
23    10/28/2012  1.276040  1.260576  1.282646  1.263713   -1     Sunday   
24    10/29/2012  1.262374  1.277135  1.265385  1.268748    0     Monday   
25    10/30/2012  1.265251  1.271375  1.270419  1.258679    0    Tuesday   
26    10/31/2012  1.259857  1.260576  1.257833  1.235305    0  Wednesday   
27     11/1/2012  1.199438  1.191103  1.201736  1.202941   -1   Thursday   
28     11/2/2012  1.193325  1.194342  1.131614  1.108727    0     Friday   
29     11/4/2012  1.106293  1.082033  1.127299  1.102254   -1     Sunday   
...          ...       ...       ...       ...       ...  ...        ...   
1613  12/22/2017 -0.339433 -0.341996 -0.321528 -0.316359    0     Friday   
1614  12/26/2017 -0.335477 -0.296640 -0.317932 -0.272848    0    Tuesday   
1615  12/27/2017 -0.283331 -0.302399 -0.282691 -0.289749    0  Wednesday   
1616  12/28/2017 -0.289804 -0.304559 -0.273701 -0.283636    0   Thursday   
1617  12/29/2017 -0.284769 -0.280801 -0.257879 -0.258104    0     Friday   
1618    1/2/2018 -0.270384 -0.269642 -0.254642 -0.268892    0    Tuesday   
1619    1/3/2018 -0.270743 -0.243005 -0.248889 -0.223223    0  Wednesday   
1620    1/4/2018 -0.222193 -0.234366 -0.205018 -0.214953    0   Thursday   
1621    1/5/2018 -0.219316 -0.240125 -0.217963 -0.231134    0     Friday   
1622    1/7/2018 -0.225430 -0.248764 -0.199624 -0.225021   -1     Sunday   
1623    1/8/2018 -0.226149 -0.244445 -0.211490 -0.225381    0     Monday   
1624    1/9/2018 -0.218237 -0.197649 -0.202141 -0.187983    0    Tuesday   
1625   1/10/2018 -0.177958 -0.194769 -0.164383 -0.174318    0  Wednesday   
1626   1/11/2018 -0.176879 -0.170292 -0.155393 -0.172160    0   Thursday   
1627   1/12/2018 -0.176879 -0.174611 -0.170137 -0.150225    0     Friday   
1628   1/14/2018 -0.150626 -0.175331 -0.131300 -0.155619   -1     Sunday   
1629   1/15/2018 -0.156020 -0.158773 -0.135615 -0.136201    0     Monday   
1630   1/16/2018 -0.144512 -0.167412 -0.161506 -0.176116    0    Tuesday   
1631   1/17/2018 -0.169686 -0.186850 -0.171575 -0.167845    0  Wednesday   
1632   1/18/2018 -0.163213 -0.185410 -0.162585 -0.170362    0   Thursday   
1633   1/19/2018 -0.181914 -0.205208 -0.181284 -0.195534    

In [7]:
import descriptive_statistics as ds

In [8]:
ds.summary(df)

Date
Count :  1643
Unique :  1643
Top :  1


Open
Count :  1643
Min :  27.99
1st Q :  49.925
Median :  61.68
3rd Q :  106.97
Max :  117.96
Mean :  74.06831405964707
St. dev :  27.80608273465092


High
Count :  1643
Min :  28.75
1st Q :  50.67
Median :  62.7
3rd Q :  107.845
Max :  118.29
Mean :  74.78076080340847
St. dev :  27.780344052611788


Low
Count :  1643
Min :  27.1
1st Q :  49.25
Median :  60.63
3rd Q :  106.455
Max :  117.74
Mean :  73.32127814972615
St. dev :  27.808711385783646


Close
Count :  1643
Min :  27.79
1st Q :  49.92
Median :  61.87
3rd Q :  107.03
Max :  118.04
Mean :  74.04758368837497
St. dev :  27.808848624480497


Vol
Count :  1643
Min :  0
1st Q :  48471.5
Median :  113728.0
3rd Q :  159089.0
Max :  522586
Mean :  108013.22458916616
St. dev :  72296.2539506527


Weekday
Count :  1643
Unique :  6
Top :  1


Month
Count :  1643
Unique :  12
Top :  1


Year
Count :  1643
Min :  2012
1st Q :  2014.0
Median :  2015.0
3rd Q :  2016.0
Max :  2018
Mean :  2014.90018

In [9]:
import pivots

In [10]:
pivots.pivoting(df, 'Date', 'Weekday', 'Open')

array([[112.14, 0, 0, 0, 0, 0],
       [0, 111.4, 0, 0, 0, 0],
       [0, 0, 110.55, 0, 0, 0],
       ...,
       [0, 0, 70.18, 0, 0, 0],
       [0, 0, 0, 70.09, 0, 0],
       [0, 0, 0, 0, 69.01, 0]], dtype=object)

In [11]:
# ete ham toxern en krknvox ham syunery petqa nory grvi anunn e kdnenq pivotingtable

In [12]:
df1 = pd.DataFrame({'foo': ['one', 'one', 'one', 'two', 'two',
                           'two'],
                   'bar': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'baz': [1, 2, 3, 4, 5, 6],
                   'zoo': ['x', 'y', 'z', 'q', 'w', 't']})

In [13]:
pivots.pivoting(df1, 'foo', 'bar', 'baz')

array([[1, 2, 3],
       [4, 5, 6]], dtype=object)

In [14]:
pivots.pivvottable(df, 'Month', 'Weekday', 'Open', 'median')

array([[60.95 , 64.   , 59.08 , 62.88 , 64.13 , 60.98 ],
       [52.135, 52.2  , 52.325, 52.395, 51.66 , 51.515],
       [63.35 , 63.58 , 63.43 , 62.81 , 62.93 , 62.64 ],
       [59.735, 58.56 , 58.985, 58.035, 58.98 , 58.925],
       [62.995, 56.96 , 62.305, 68.52 , 61.8  , 66.54 ],
       [56.165, 57.65 , 55.785, 57.44 , 57.675, 58.8  ],
       [63.34 , 63.905, 63.965, 63.62 , 63.32 , 64.69 ],
       [58.11 , 57.85 , 60.05 , 56.33 , 56.13 , 56.04 ],
       [66.75 , 65.82 , 65.855, 67.17 , 65.6  , 66.16 ],
       [74.965, 63.68 , 63.52 , 70.46 , 64.12 , 63.355],
       [72.575, 60.38 , 57.95 , 83.36 , 85.13 , 86.1  ],
       [54.915, 56.19 , 55.59 , 55.02 , 54.625, 54.18 ]])

In [15]:
# if you would like to compare results
df.groupby(['Month', "Weekday"]).median()

Open    High     Low   Close       Vol    Year
Month Weekday                                                    
Apr   Friday     60.950  61.840  60.140  61.410  144775.5  2015.0
      Monday     64.000  64.400  62.100  63.480  123567.0  2015.0
      Sunday     59.080  59.080  58.870  58.890     311.0  2015.0
      Thursday   62.880  64.950  62.000  63.940  122943.0  2015.0
      Tuesday    64.130  64.505  62.775  63.175  127947.0  2015.0
      Wednesday  60.980  63.400  60.710  62.780  162212.5  2015.0
Aug   Friday     52.135  52.820  51.670  52.660  123614.0  2015.0
      Monday     52.200  52.470  50.810  51.655  139186.0  2015.0
      Sunday     52.325  52.485  52.315  52.385     217.5  2015.0
      Thursday   52.395  52.895  51.640  52.030  145392.5  2015.0
      Tuesday    51.660  52.035  50.930  51.535  137707.5  2015.0
      Wednesday  51.515  52.060  50.850  51.480  161579.0  2015.0
Dec   Friday     63.350  63.940  62.590  63.400  102214.0  2015.0
      Monday     63.580  64.930  63.000  64.690   95204.0  2014.0
      Sunday     63.430  63.535  63.385  63.450     259.0  2014.0
      Thursday   62.810  63.700  62.010  63.310  103478.0  2015.0
      Tuesday    62.930  63.530  62.595  63.100   98884.5  2014.5
      Wednesday  62.640  63.400  61.130  61.220  106912.0  2015.0
Feb   Friday     59.735  61.460  59.450  60.755  107543.0  2015.0
      Monday     58.560  60.590  57.980  58.830  108049.0  2015.0
      Sunday     58.985  59.550  58.820  59.245     314.0  2015.0
      Thursday   58.035  60.450  57.065  59.725  120116.0  2015.0
      Tuesday    58.980  60.185  57.645  58.385  126435.5  2015.0
      Wednesday  58.925  60.655  57.025  58.025  135110.0  2015.0
Jan   Friday     62.995  63.325  61.770  62.185  131138.0  2015.0
      Monday     56.960  57.000  56.820  56.820  107139.0  2016.0
      Sunday     62.305  62.430  62.290  62.380     347.0  2015.5
      Thursday   68.520  68.950  68.210  68.665  121962.0  2015.0
      Tuesday    61.800  62.830  60.820  61.065  163021.5  2016.0
      Wednesday  66.540  68.030  66.400  67.840  139893.0  2015.0
...                 ...     ...     ...     ...       ...     ...
Mar   Friday     58.110  58.320  55.520  55.915  117502.5  2015.0
      Monday     57.850  58.575  57.135  57.835  111930.0  2015.0
      Sunday     60.050  60.130  59.680  59.750     437.0  2015.0
      Thursday   56.330  57.795  55.665  56.105  128051.0  2015.0
      Tuesday    56.130  56.720  55.205  55.455  132915.0  2015.0
      Wednesday  56.040  57.110  55.470  56.330  146129.5  2015.0
May   Friday     66.750  66.930  65.370  66.510  120952.0  2015.0
      Monday     65.820  66.375  64.865  65.705   75986.0  2015.0
      Sunday     65.855  65.905  65.780  65.810     173.0  2015.0
      Thursday   67.170  68.495  66.070  66.565  139482.5  2015.0
      Tuesday    65.600  66.045  63.620  64.170  140471.0  2015.0
      Wednesday  66.160  66.850  65.485  66.000  152508.5  2015.0
Nov   Friday     74.965  76.580  73.270  74.810  120909.0  2014.0
      Monday     63.680  64.440  62.700  64.270  117796.0  2015.0
      Sunday     63.520  63.770  63.520  63.700     343.0  2015.0
      Thursday   70.460  70.855  67.255  68.375  127786.0  2014.5
      Tuesday    64.120  64.650  63.500  63.690  137199.0  2015.0
      Wednesday  63.355  64.115  62.785  63.405  134320.5  2015.0
Oct   Friday     72.575  73.300  71.590  73.085  130525.0  2014.5
      Monday     60.380  60.700  59.910  60.530  134279.0  2015.0
      Sunday     57.950  58.050  57.920  57.980     453.0  2015.0
      Thursday   83.360  87.100  82.930  86.100  128722.0  2014.0
      Tuesday    85.130  86.380  84.830  86.000  135021.0  2014.0
      Wednesday  86.100  87.070  84.470  84.680  137285.0  2014.0
Sep   Friday     54.915  55.360  54.215  54.615  136796.0  2015.0
      Monday     56.190  57.600  55.760  56.980  115027.0  2015.0
      Sunday     55.590  55.590  55.470  55.510     189.0  2015.0
      Thursday   55.020  55.990  54.930  55.280  127900.0  

In [16]:
import grouppby as gb

In [17]:
gb.grouppby(df, 'Year', 'median')

['Open', 'High', 'Low', 'Close', 'Vol', 'Year']
2012 [109.535, 110.32, 108.69999999999999, 109.695, 63025.5, 2012.0]
2013 [108.59, 109.44, 107.82499999999999, 108.66, 74789.5, 2013.0]
2014 [106.59, 107.34, 105.93, 106.62, 88615.5, 2014.0]
2015 [53.24, 54.325, 52.394999999999996, 53.135, 128171.0, 2015.0]
2016 [46.76, 47.49, 46.15, 46.86, 161152.0, 2016.0]
2017 [54.5, 55.36, 53.9, 54.5, 145344.0, 2017.0]
2018 [69.15, 69.59, 68.59, 69.2, 135444.0, 2018.0]


In [9]:
df2 = pd.DataFrame({'foo': ['one', 'one', 'one', 'two', 'two',
                           'two'],
                   'bar': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'baz': [np.nan, 2, 3, 4, 5, 6],
                   'zoo': [np.nan, 2, 3, np.nan, 5, 6]})

In [7]:
import nafill as na

In [8]:
na.nafill(df2, 'baz', 'zoo')

C:\Users\Gurgen\Desktop\Master Degree\1 course\1 half\Python\Group_Project\Marianna_Gurgen\nafill.py:20: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  df[columns[i]][j] = df[columns[i]].mean()


foo bar  baz  zoo
0  one   A  4.0  4.0
1  one   B  2.0  2.0
2  one   C  3.0  3.0
3  two   A  4.0  4.0
4  two   B  5.0  5.0
5  two   C  6.0  6.0

In [9]:
df.head()

Date    Open    High     Low   Close    Vol    Weekday Month  Year
0  10/1/2012  112.14  113.27  110.76  111.40  80055     Monday   Oct  2012
1  10/2/2012  111.40  111.70  110.55  110.55  29332    Tuesday   Oct  2012
2  10/3/2012  110.55  110.59  106.95  107.34  56307  Wednesday   Oct  2012
3  10/4/2012  107.44  111.79  107.24  111.36  61664   Thursday   Oct  2012
4  10/5/2012  111.27  112.09  109.64  111.13  51704     Friday   Oct  2012

In [6]:
import changecalculator as cc

In [8]:
cc.change(df, "Open", "Close")

[-0.0066207632023428204,
 -0.007659420189728447,
 -0.029466540554772463,
 0.03583564437112733,
 -0.001258992972053974,
 -0.0008103363339021316,
 0.003602958320214292,
 0.016635174339790504,
 0.0012366400303999987,
 0.011920554865337928,
 -0.012881920238949613,
 -0.0037940664033048106,
 0.012127752126120807,
 -0.005174769254888084,
 -0.006690754777625917,
 -0.006029456109931565,
 -0.018055734168431523,
 -0.0011835937103506714,
 0.0005466472439332853,
 -0.011202026973248522,
 -0.004627067296619175,
 0.00647251450561752,
 0.010538470956883752,
 -0.0032915820155006528,
 0.001464531154215351,
 -0.00183234132806144,
 -0.006436803833479199,
 0.0007444630904041356,
 -0.022345718352682044,
 -0.0012408725879900964,
 0.02125829971639489,
 0.03023550441169595,
 -0.03447658668853362,
 0.001696673043458426,
 0.022871952769996616,
 -0.0027662534928900736,
 -0.004349643616765545,
 -0.004834520386869878,
 0.014448709265365341,
 -0.008598823265909735,
 0.012274622295345143,
 0.0022857152808560825,
 0.01

In [11]:
np.log(df["Close"][0]/df["Open"][0])

-0.0066207632023428204